# schema https://golangci-lint.run/usage/configuration
# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: false

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true

  go: '1.18'

linters:
  enable-all: true
  disable:
    - gomnd # Magic numbers
    - lll
    - exhaustruct # Not needed for now.
    - tagliatelle # Checks json tags, sometimes we use it to transform unwanted json.
    - interfacer # The repository of the linter has been archived by the owner.
    - scopelint # The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
    - golint # The repository of the linter has been archived by the owner.  Replaced by revive.
    - maligned # The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'.
    - structcheck # The owner seems to have abandoned the linter. Replaced by unused.
    - nosnakecase # The repository of the linter has been deprecated by the owner. Replaced by revive(var-naming).
    - varcheck # The owner seems to have abandoned the linter. Replaced by unused.
    - deadcode # The owner seems to have abandoned the linter. Replaced by unused.
    - ifshort # The repository of the linter has been deprecated by the owner.
    - exhaustivestruct # Competes with validators.
    - gci # imports sorter, conflicts with other sorters.
    - ireturn
    - contextcheck
    - misspell

linters-settings:
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 90
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: -1
  godox:
    # Report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging.
    # Default: ["TODO", "BUG", "FIXME"]
    keywords:
      - FIXME
      - BUG
      - WARN
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-around that should be removed before merging
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 15

    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    # package-average: 0.5

    # Should ignore tests.
    # Default: false
    skip-tests: true

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Fix found issues (if it's supported by the linter)
  fix: false
