# schema https://golangci-lint.run/usage/configuration
# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 1m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: false

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: true

  go: '1.18'

linters:
  enable-all: true
  disable:
    - gomnd # Magic numbers
    - lll
    - exhaustruct # Not needed for now.
    - tagliatelle # Checks json tags, sometimes we use it to transform unwanted json.
    - interfacer # The repository of the linter has been archived by the owner.
    - scopelint # The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
    - golint # The repository of the linter has been archived by the owner.  Replaced by revive.
    - maligned # The repository of the linter has been archived by the owner.  Replaced by govet 'fieldalignment'.
    - exhaustivestruct # Competes with validators.
    - gci # imports sorter, conflicts with other sorters.
    - ireturn
    - contextcheck
    - misspell

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Fix found issues (if it's supported by the linter)
  fix: false